version: "3.3"

services:
  server:
    build: ./server
    ports:
      - "3005:3005"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - PORT=3005
      - NODE_PATH=/app
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - './client:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_PATH=/app
    links:
      - server
    depends_on:
      - server
    stdin_open: true
  redis:
    image: redis
    ports:
      - "6379:6379"

